import { useEffect } from 'react';
import '../styles/globals.css';
import CssBaseline from '@material-ui/core/CssBaseline';
import { ThemeProvider } from '@material-ui/core/styles';
import theme from '../theme';
import Head from 'next/head';
import Layout from '../components/Layout';

function MyApp({ Component, pageProps }) {
  useEffect(() => {
	  const jssStyle = document.querySelector('#jss-server-side');
	  
	  if(jssStyle) {
		jssStyle.parentElement.removeChild(jssStyle);
	  }
  }, [])
	
  return (
	<>
		<Head>
			<title>UI Lab Test Task</title>
			<meta name="description" content="Generated by create next app" />
			<link rel="icon" href="/favicon.ico" />
		</Head>
		
		<ThemeProvider theme={theme}>
			<CssBaseline />
			<Layout>
				<Component {...pageProps} />
			</Layout>
		</ThemeProvider>
	</>
  )
}

export default MyApp;
